name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        github_token: ${{ secrets.LikeLion_Create_Pull_Request }}
        head: ${{ github.ref }}
        base: main
        title: ${{ github.event.head_commit.message }}
